Get-AppxPackage -allusers Microsoft.BingWeather* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.GetHelp* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Microsoft3DViewer* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MixedReality.Portal* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Office.OneNote* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.People* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Print3D* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ScreenSketch* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.SkypeApp* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.StorePurchaseApp* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Wallet* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsAlarms* | Remove-AppxPackage
Get-AppxPackage -allusers microsoft.windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsMaps* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsSoundRecorder* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsStore* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Xbox.TCUI* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxApp* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxGameOverlay* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxGamingOverlay* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxIdentityProvider* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxSpeechToTextOverlay* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.YourPhone* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ZuneMusic* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ZuneVideo* | Remove-AppxPackage
Get-AppxPackage -AllUsers *ActiproSoftwareLLC* | Remove-AppxPackage
Get-AppxPackage -AllUsers *AdobeSystemsIncorporated.AdobePhotoshopExpress* | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingNews* | Remove-AppxPackage
Get-AppxPackage -AllUsers *CandyCrush* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Duolingo* | Remove-AppxPackage
Get-AppxPackage -AllUsers *EclipseManager* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Facebook* | Remove-AppxPackage
Get-AppxPackage -AllUsers *king.com.FarmHeroesSaga* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Flipboard* | Remove-AppxPackage
Get-AppxPackage -AllUsers *HiddenCityMysteryofShadows* | Remove-AppxPackage
Get-AppxPackage -AllUsers *HuluLLC.HuluPlus* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Pandora* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Plex* | Remove-AppxPackage
Get-AppxPackage -AllUsers *ROBLOXCORPORATION.ROBLOX* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Spotify* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Netflix* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.SkypeApp* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Twitter* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Wunderlist* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.549981C3F5F10* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.DesktopAppInstaller* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.HEIFImageExtension* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftEdge.Stable* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MSPaint* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.VCLibs.140.00* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.VP9VideoExtensions* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WebMediaExtensions* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WebpImageExtension* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.Photos* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsCalculator* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsCamera* | Remove-AppxPackage
